### ISSUE TITLE
current nuget VL.RCP (0.2.3) has old RCPsharp dependency

### ISSUE THREAD

**Issue by mhusinsky** [rabbitControl/VL.IO.RCP#3]
installing VL.RCP from nuget.org will download version 0.2.3-alpha, which has RCPSharp.0.2.5-alpha as dependency. current version is RCPSharp.0.2.11-alpha, which apparently fixes a problem with not closing a socket when changing ports.

would be good to update the dependency in the nuget.

**Comment by joreg** [comment]
thanks, this has meanwhile been fixed in new nugets: VL.IO.RCP
