### ISSUE TITLE
2 of 3 help patches not working with latest vvvv 2021.4.11-1332

### ISSUE THREAD

**Issue by seltzdesign** [rabbitControl/VL.IO.RCP#4]
Just trying out the help patches of the RCP nuget and noticed that 2 of them do not work.

It's the patch "How to expose an image" and "How to expose parameters over the internet".

Both result in the client connecting, but not showing anything. Console is not showing any error messages.

<img width="1073" alt="image" src="https://user-images.githubusercontent.com/6575829/201118188-db622688-92c9-40e3-9a0b-749093fba52e.png">

<img width="1292" alt="image" src="https://user-images.githubusercontent.com/6575829/201118832-efe2ea9e-bec4-4437-8d1b-ae0f773e172e.png">

The 3rd help patch "Expose Parameters" works fine.

Thanks for investigating!

**Comment by joreg** [comment]
just tested this with 2021.4.11 preview-1138 and VL.IO.RCP 0.4.10-alpha and i cannot confirm the issues you see.

please try again with those exact versions and report back.

**Comment by seltzdesign** [comment]
Tried again with the latest preview 1138 and RCP version (was already installed) and I can confirm the image example is not working. Tried different browsers with same result. When I tried on a different machine it worked fine.

How can we start to debug this? VVVV says its connected, browser console is not showing any errors.

**Comment by joreg** [comment]
please reopen if this persists with latest version of vvvv and vl.io.rcp
