### ISSUE TITLE
VVVV Helpbrowser should show IO.RCP when searching for "rabbit"

### ISSUE THREAD

**Issue by mhusinsky** [rabbitControl/VL.IO.RCP#6]
currently it does not (IO.RCP 0.4.10 @ gamma 2022.5-0634)

**Comment by joreg** [comment]
this works in latest version of this pack. as tags have been applied to individual helps. we cannot have packs show up as a whole when their tags are found because this would give too many false positives (example: tag "video" would already show full vl.opencv pack
