### ISSUE TITLE
All parameters are always sent on change

### ISSUE THREAD

**Issue by seltzdesign** [rabbitControl/VL.IO.RCP#7]
As written here: https://discourse.vvvv.org/t/rcp-always-sends-all-parameters-to-client/21284, in the current version (0.4.11) with the latest version of vvvv (tested with 2022.5.0-0485) whenever any parameter updates in the web client or in VL, all parameters are always sent. This leads to major performance hits when dealing with many parameters. Additionally it can actually crash the network card and/or router.

Thanks for looking into.

Tested using Brave browser on Windows 11.

**Comment by joreg** [comment]
thanks for pointing this out. should be fixed in VL.IO.RCP version 0.5.0
